apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  sessionAffinity: None
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 8000
      nodePort: 30001
  selector:
    app: demo
  type: NodePort
