apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: service2
spec:
  sessionAffinity: None
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8000
  selector:
    app: service2
  type: ClusterIP
