name: Docker

on:
  push:
    branches:
      - 'main'

jobs:
  services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push service1
        uses: docker/build-push-action@v3
        with:
          context: k8s/02_two_services/service1
          platforms: linux/amd64
          push: true
          tags: ghcr.io/dliebg/thi_cnd_playground/k8s/02_two_services/service1:latest
      
      - name: Build and push service2
        uses: docker/build-push-action@v3
        with:
          context: k8s/02_two_services/service2
          platforms: linux/amd64
          push: true
          tags: ghcr.io/dliebg/thi_cnd_playground/k8s/02_two_services/service2:latest
